version: "3.8"
services:
  db:
    build: ./docker-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seguridad_apps_web
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    hostname: external_client
    networks:
        utn-frba:
            ipv4_address: 192.17.0.52
  web:
    build: ./
    environment:
      MYSQL_DATABASE: seguridad_apps_web
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: 192.17.0.52
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure
    hostname: external_client
    networks:
         utn-frba:
            ipv4_address: 192.17.0.51
volumes: 
  db:

networks:
    utn-frba:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.17.0.0/24
